### PR TITLE
Fix package mappings for Debian systems

### LINKED ISSUE #384: Implement correct mapping of packages reported by 'profileupdate' for Ubuntu/Debian
The package information reported by `packages.profileupdate` for Ubuntu/Debian differs from SUSE OSs. As a result, for example, package architectures cannot be mapped by Uyuni correctly, therefore having problems to display package information, finding out package updates, etc.

Original findings by @rpasche:

> A further "problem" is the architecture. The architecutre returned from a x86_64 Debian system is
amd64. But within Uyuni (and Spacewalk), x86_64 Debian systems have an architecture name of
amd64-deb.

> In my tests, I still have a problem, when I do NOT modify the architecture. If I return the original architecture (here, amd64 for a x86_64 Debian system), I won't get package update suggestions, as the system will be "up-to-date" within Uyuni (also the software packages links are broken). But if I modify the architecture (and append -deb, so it returns amd64-deb) to the original architecture, I see possible software packages updates and the software package links are correct.

Although we can choose to handle this on different levels (states, salt modules, etc.), I belive the most convenient place would be the Java code, since we often tend to do this kind of mappings in there.

The goal of this task should be to add necessary mappings to the profile update handling code in Java for package architectures (e.g. `amd64` to `amd64-deb`) and identify if any other attributes need to be mapped and implement accordingly.

A good place to start would be the following entry points in Java:
- [com.suse.manager.utils.SaltUtils.java#updatePackages](https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/suse/manager/utils/SaltUtils.java#L1210)
- [com.suse.manager.utils.SaltUtils.java#createPackageFromSalt](https://github.com/uyuni-project/uyuni/blob/master/java/code/src/com/suse/manager/utils/SaltUtils.java#L1364)

## Checklist
- [x] Map package architectures on profile update `amd64 -> amd64-deb`
- [x] Fix version definitons when calling package states (install, update, remove, etc.)

## Links
- [Debian's package versioning policy](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version)

### PR DESCRIPTION
**Pull request by cbbayburt**
Fix package version/architecture mappings for Debian systems.

## Problem
We need to fix mappings for the version and architecture of Debian packages both ways, while conforming to Uyuni's internal rules about package EVRAs.

Existing conditions/constraints:
1. Debian architectures have a suffix "-deb" on their names and labels.
2. Unlike rpm, deb packages may not have a 'release' in their version strings. `repo-sync` appends "-X" to such packages as the release string.

In order to get the packages recognized and matched by Uyuni, we need to apply those conditions on packages retrieved from the profile update.

On the other hand, these mappings must be reversed when calling package states (pkginstall, pkgremove, etc.)

## Test coverage
- [x] Unit tests

## Links

Fixes #384

### CODE REVIEW

**Comment by mbologna** [comment]
gitarro no changelog needed !!!

**Comment by mbologna** [comment]
gitarro no changelog needed !!!

**Comment by cbbayburt** [comment]
@mateiw ready for a final review now

File: java/code/src/com/suse/manager/utils/PackageUtils.java [hunk 1]
```diff
@@ -41,6 +43,40 @@ public static boolean isTypeDeb(Package pkg) {
         return "deb".equals(getArchTypeLabel(pkg));
     }
 
+    /**
+     * Get the channel architecture as a universal arch string, practically
+     * stripping away any arch type suffixes (e.g. "-deb")
+     * @param arch the package arch
+     * @return an package architecture string
+     */
+    public static String getUniversalArchString(PackageArch arch) {
```
Comment (moio) [inline java/code/src/com/suse/manager/utils/PackageUtils.java]: Is there a particular reason not to put this method in `PackageArch`?

File: java/code/src/com/suse/manager/utils/PackageUtils.java [hunk 2]
```diff
@@ -41,6 +43,40 @@ public static boolean isTypeDeb(Package pkg) {
...
+    }
+
+    /**
+     * Return an EVR string representation in the format "[epoch:]version-release",
+     * stripping away any dummy release strings (e.g. "-X")
+     *
+     * @param evr the package evr
+     * @return string representation of epoch, version and release
+     */
+    public static String getUniversalEvrString(PackageEvr evr) {
```
Comment (moio) [inline java/code/src/com/suse/manager/utils/PackageUtils.java]: Is there a particular reason not to put this method in `PackageEvr`? In particular, do we really need both this and the original `toString`?

File: java/code/src/com/suse/manager/utils/PackageUtils.java [hunk 3]
```diff
@@ -41,6 +43,40 @@ public static boolean isTypeDeb(Package pkg) {
         return "deb".equals(getArchTypeLabel(pkg));
     }
 
+    /**
+     * Get the channel architecture as a universal arch string, practically
```
Comment (moio) [inline java/code/src/com/suse/manager/utils/PackageUtils.java]: Given the definition of "universal" is new to this PR, I would spend a line describing it in comments.

Eg. "Universal means:..."

(I know this is implied by the code and existing comments - this is just to make life easier to future readers)

File: java/code/src/com/suse/manager/utils/SaltUtils.java [hunk 4]
```diff
@@ -1097,14 +1097,10 @@ private void handleImagePackageProfileUpdate(ImageInfo imageInfo,
...
-                packages.stream().forEach(pkg -> {
-                    createImagePackageFromSalt(pkg.getName(),
-                            pkg.getEpoch().equals(StringUtils.EMPTY) ? null :
-                                    pkg.getEpoch(),
-                            pkg.getRelease(), pkg.getVersion(),
-                            Optional.of(instantNow),
-                            Optional.of(pkg.getArch()), imageInfo);
-                });
+                packages.forEach(pkg -> createImagePackageFromSalt(pkg.getName(),
+                        PackageEvrFactory.lookupOrCreatePackageEvr(StringUtils.trimToNull(pkg.getEpoch()),
```
Comment (moio) [inline java/code/src/com/suse/manager/utils/SaltUtils.java]: Nitpick: Is there a particular reason to move `lookupOrCreatePackageEvr` here, instead of leaving it in `createImagePackageFromSalt`? I somewhat like the idea `createImagePackageFromSalt` is the method responsible for writing into the database.

File: susemanager-utils/susemanager-sls/salt/packages/pkginstall.sls [hunk 5]
```diff
@@ -7,7 +7,9 @@ pkg_installed:
 {%- endif %}
     -   pkgs:
 {%- for pkg, arch, version in pillar.get('param_pkgs', []) %}
-    {%- if grains.get('__suse_reserved_pkg_all_versions_support', False) %}
+    {%- if grains['os_family'] == 'Debian' %}
+        - {{ pkg }}:{{ arch }}: {{ version }}
```
Comment (moio) [inline susemanager-utils/susemanager-sls/salt/packages/pkginstall.sls]: Is it intentional that in Debian `pkg` and `arch` are separated by colon while in RPM-based distros they are separated by dot?

File: java/code/src/com/suse/manager/utils/PackageUtils.java [hunk 6]
```diff
@@ -41,6 +43,40 @@ public static boolean isTypeDeb(Package pkg) {
...
+     * stripping away any dummy release strings (e.g. "-X")
+     *
+     * @param evr the package evr
+     * @return string representation of epoch, version and release
+     */
+    public static String getUniversalEvrString(PackageEvr evr) {
+        StringBuilder builder = new StringBuilder();
+        if (StringUtils.isNumeric(evr.getEpoch())) {
+            builder.append(evr.getEpoch());
+            builder.append(":");
```
Comment (mbologna) [inline java/code/src/com/suse/manager/utils/PackageUtils.java]: Given the number of times this method is called, I think that we can gain something in terms of performance by using the `char` representation and concatenating the two calls:

```
            builder.append(evr.getEpoch()).append(':');
```

File: java/code/src/com/suse/manager/utils/PackageUtils.java [hunk 7]
```diff
@@ -41,6 +43,40 @@ public static boolean isTypeDeb(Package pkg) {
...
+        }
+        builder.append(evr.getVersion());
+
+        // Strip dummy release string
+        if (!evr.getRelease().equals("X")) {
+            builder.append("-");
```
Comment (mbologna) [inline java/code/src/com/suse/manager/utils/PackageUtils.java]: Same as above:

```
            builder.append('-').append(evr.getRelease());
```

File: java/code/src/com/suse/manager/utils/PackageUtils.java (hunk 2 above)
Comment (cbbayburt) [reply java/code/src/com/suse/manager/utils/PackageUtils.java]: Not really, but `toString` wouldn't be a good idea since we do some conditional substring operation, whereas `toString` automatically means it would be output as-is no matter what.

Moving both methods to respective classes with names `toUniversal...String`

File: java/code/src/com/suse/manager/utils/PackageUtils.java (hunk 3 above)
Comment (cbbayburt) [reply java/code/src/com/suse/manager/utils/PackageUtils.java]: Added a phrase in the descriptions

File: java/code/src/com/suse/manager/utils/SaltUtils.java (hunk 4 above)
Comment (cbbayburt) [reply java/code/src/com/suse/manager/utils/SaltUtils.java]: The aim was to keep the string sanitation in a single place.

I restructured the functions. Just a little more verbose, but should be more readable now.

File: susemanager-utils/susemanager-sls/salt/packages/pkginstall.sls (hunk 5 above)
Comment (cbbayburt) [reply susemanager-utils/susemanager-sls/salt/packages/pkginstall.sls]: Yes, it's intentional. It was a constraint from Salt side. I believe it was because debian package names are allowed to have dots in them.

See: https://github.com/openSUSE/salt/commit/2e9029db72879b30979a59e057d8712399ef567f#diff-f28fd94bb04c597a37eaea3b885be3bcR222

File: java/code/src/com/suse/manager/utils/SaltUtils.java [hunk 8]
```diff
@@ -1361,41 +1357,51 @@ private static void handleHardwareProfileUpdate(MinionServer server,
...
-        pkg.setArch(PackageFactory.lookupPackageArchByLabel(info.getArchitecture().get()));
+        pkg.setEvr(parsePackageEvr(serverArchTypeLabel, info));
         pkg.setInstallTime(new Date(info.getInstallDateUnixTime().get() * 1000));
         pkg.setName(PackageFactory.lookupOrCreatePackageByName(name));
         pkg.setServer(server);
+
+        // Add -deb suffix to architectures for Debian systems
+        String pkgArch = info.getArchitecture().get();
+        if (serverArchTypeLabel.equals("deb")) {
+            pkgArch += "-deb";
```
[the remark this answers is not in the document]
Comment (cbbayburt) [reply java/code/src/com/suse/manager/utils/SaltUtils.java]: It is called per package returned from profile update, which would be in 1000s for each system. But I can't see how `StringBuffer` would improve this case. IIUC, it won't reflect any changes in the bytecode since this is not a loop by itself.

File: java/code/src/com/suse/manager/utils/PackageUtils.java (hunk 7 above)
Comment (cbbayburt) [reply java/code/src/com/suse/manager/utils/PackageUtils.java]: Done

File: java/code/src/com/suse/manager/utils/PackageUtils.java (hunk 6 above)
Comment (cbbayburt) [reply java/code/src/com/suse/manager/utils/PackageUtils.java]: Done

File: java/code/src/com/suse/manager/utils/SaltUtils.java [hunk 9]
```diff
@@ -1361,41 +1357,51 @@ private static void handleHardwareProfileUpdate(MinionServer server,
...
-        pkg.setEvr(evr);
-        pkg.setArch(PackageFactory.lookupPackageArchByLabel(info.getArchitecture().get()));
+        pkg.setEvr(parsePackageEvr(serverArchTypeLabel, info));
         pkg.setInstallTime(new Date(info.getInstallDateUnixTime().get() * 1000));
         pkg.setName(PackageFactory.lookupOrCreatePackageByName(name));
         pkg.setServer(server);
+
+        // Add -deb suffix to architectures for Debian systems
+        String pkgArch = info.getArchitecture().get();
+        if (serverArchTypeLabel.equals("deb")) {
```
[the remark this answers is not in the document]
Comment (cbbayburt) [reply java/code/src/com/suse/manager/utils/SaltUtils.java]: Done

**Comment by cbbayburt** [comment]
@moio, @mbologna thank you very much for the reviews. I've addressed all your comments as either replies or fixup commits.

File: java/code/src/com/suse/manager/utils/SaltUtils.java (hunk 8 above)
[the remark this answers is not in the document]
Comment (moio) [reply java/code/src/com/suse/manager/utils/SaltUtils.java]: Bytecode level and object utilization will surely be different, albeit slightly.

In the current version, we are creating an initial instance of `String` (the original `pkgArch` referencing it), then we throw it into the garbage collector when we replace it with a new one (that's what `+=` does, updating `pkgArch` to point to the new `String` instance). Bytes are copied from the original `String` to the new `String`.

`StringBuffer` is definitely the wrong class to use here, as it's thread safe so its methods are synchronized. Acquiring and releasing locks takes time, so it would be slower. There is a thread-unsafe variant, `StringBuilder`, so let's look at that.

We would create a throwaway `StringBuilder`, and that internally gets a character array buffer. Assuming the buffer is big enough, the initial `pkgArch` would be copied there, and then the `"-deb"` string. At the end of the day, yet another new `String` would be allocated when calling `StringBuilder.toString()`, all characters so far copied and `StringBuilder` goes to GC.

So:
 - current implementation: one new character array allocation (for the result `String`), two string copy operations (one for the original `pkgArch` and one for `"-deb"`
 - `StringBuilder`: two new character array allocations (one for the bugger, one for the result String - assuming buffer is created big enough), three string copy operations (original `pkgArch` to buffer, `"-deb"` to buffer, buffer to result `String`)

I would say, let's tweak this only if we get a real performance problem and only if we measure that the problem is here :wink:

**Comment by moio** [comment]
+1 to proceed from my part
