### PR TITLE
Fix upgrade: wrong hardcoded db name

### LINKED ISSUE #11855: Upgrade to 2026.04 fails during upgrade of DB-Container (DB susemanager doesn't exist)
### Problem description

During the upgrade process of Uyuni the Database upgarde fails, because it wants to update a database named susemanager - not the databse uyuni.

The output of "mgradm upgrade podman": 
```
â  systemctl start uyuni-server
10:16AM ERR error="cannot configure db container: uyuni-db fails healtcheck: container didn't start within 15s or failed. Check the service status"
Error: cannot configure db container: uyuni-db fails healtcheck: container didn't start within 15s or failed. Check the service status
```

Output of systemctl status uyuni-db.service:
During the upgrade process of Uyuni the Database upgarde fails, because it wants to update a database named susemanager - not the databse uyuni.

The output of "mgradm upgrade podman": 
```
â  systemctl start uyuni-server
10:16AM ERR error="cannot configure db container: uyuni-db fails healtcheck: container didn't start within 15s or failed. Check the service status"
Error: cannot configure db container: uyuni-db fails healtcheck: container didn't start within 15s or failed. Check the service status
```

It looks like the upgrade script wnts to update a database susemanager, which doesn't exist. DB name is uyuni

### Steps to reproduce the issue

mgradm upgrade podman

### Uyuni-tools version used to deploy/manage the server (or proxy)

```bash
mgradm and mgrctl are version  5.2.9-241000.2.1.uyuni5
```

### Uyuni server version

```bash
Uyuni 2026.04
```

### Uyuni proxy version (if used)

```bash

```

### Useful logs

```bash

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by mbussolotto**
## What does this PR change?

as title 

## Codespace

Check if you already have a running container clicking on [Running CodeSpace](https://github.com/codespaces)

[Create CodeSpace](https://codespaces.new/uyuni-project/uyuni)  [About billing for Github Codespaces](https://docs.github.com/en/billing/managing-billing-for-github-codespaces/about-billing-for-github-codespaces) [CodeSpace Billing Summary](https://github.com/settings/billing/summary) [CodeSpace Limit](https://github.com/settings/billing/spending_limit)

## GUI diff

No difference.

- [x] **DONE**

## Documentation
- No documentation needed: **add explanation. This can't be used if there is a GUI diff**
- No documentation needed: only internal and user invisible changes
- Documentation issue was created: [Link for SUSE Multi-Linux Manager contributors](https://github.com/SUSE/spacewalk/issues/new?template=ISSUE_TEMPLATE_DOCUMENTATION.md&labels=documentation&projects=SUSE/spacewalk/31), [Link for community contributors](https://github.com/uyuni-project/uyuni-docs/issues/new).
- API documentation added: please review the Wiki page [Writing Documentation for the API](https://github.com/uyuni-project/uyuni/wiki/Writing-documentation-for-the-API) if you have any changes to API documentation.
- (OPTIONAL) [Documentation PR](https://github.com/uyuni-project/uyuni-docs/pulls)

- [x] **DONE**

## Test coverage
ℹ️ If a major new functionality is added, it is **strongly recommended** that tests for the new functionality are added to the Cucumber test suite
- No tests: **add explanation**
- No tests: already covered
- Unit tests were added
- Cucumber tests were added

- [x] **DONE**

## Links

Issue(s): https://github.com/uyuni-project/uyuni/issues/11855

- [x] **DONE**

## Changelogs

Make sure the changelogs entries you are adding are compliant with https://github.com/uyuni-project/uyuni/wiki/Contributing#changelogs and https://github.com/uyuni-project/uyuni/wiki/Contributing#uyuni-projectuyuni-repository

If you don't need a changelog check, please mark this checkbox:

- [ ] No changelog needed

If you uncheck the checkbox after the PR is created, you will need to re-run `changelog_test` (see below)

## Re-run a test

If you need to re-run a test, please mark the related checkbox, it will be unchecked automatically once it has re-run:

- [ ] Re-run test "changelog_test"
- [ ] Re-run test "backend_unittests_pgsql"
- [ ] Re-run test "java_pgsql_tests"
- [ ] Re-run test "schema_migration_test_pgsql"
- [ ] Re-run test "susemanager_unittests"
- [ ] Re-run test "frontend_checks"
- [ ] Re-run test "spacecmd_unittests"

# Before you merge

Check [How to branch and merge properly](https://github.com/uyuni-project/uyuni/wiki/How-to-branch-and-merge-properly)!

### CODE REVIEW

File: containers/server-postgresql-image/root/docker-entrypoint-upgdb.d/get_pgsql_disk_severity.sh [hunk 1]
```diff
@@ -7,11 +7,13 @@
 DB_CRIT=${DISKTHRESHOLD:-95}
 DB_WARN=${DISKCHECKALERT:-90}
 
+productdb=$(sed -n "s/^\s*db_name\s*=\s*\([^ ]*\)\s*$/\1/p" /etc/rhn/rhn.conf)
```
Comment (mbussolotto) [inline containers/server-postgresql-image/root/docker-entrypoint-upgdb.d/get_pgsql_disk_severity.sh]: cannot work, since /etc/rhn/rhn.conf is not present in db

**Review by aaannz — APPROVED** [review]
LGTM given time constrains.

But IMO it would be better to be in one helper function.
Also using `-A` option would drop the spaces and the matching function then can be simpler.
Similarly using different field separator (option -F) we can use something safer then `|` in case this is sometime later preprocessed.

**Comment by mbussolotto** [comment]
tested upgrade of just the db image, from the current stable 
```
CONTAINER ID  IMAGE                                                                                                                        COMMAND               CREATED        STATUS                  PORTS                                                                                                                                                                                 NAMES
a3a284332cf9  registry.opensuse.org/home/mbussolotto/branches/systemsmanagement/uyuni/master/containerfile/uyuni/server-postgresql:latest  postgres              2 minutes ago  Up 2 minutes (healthy)  0.0.0.0:5432->5432/tcp                                                                                                                                                                uyuni-db
bec94ad3aa85  registry.opensuse.org/uyuni/server:latest                                                                                    /docker-entrypoin...  2 minutes ago  Up 2 minutes (healthy)  0.0.0.0:80->80/tcp, 0.0.0.0:443->443/tcp, 0.0.0.0:4505-4506->4505-4506/tcp, 0.0.0.0:5556-5557->5556-5557/tcp, 0.0.0.0:9100->9100/tcp, 0.0.0.0:9187->9187/tcp, 0.0.0.0:9800->9800/tcp  uyuni-server
```
evertyhing seems fine.

@deneb-alpha
